### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by myka-p** [myka-p/cpnt260-a2#1]
# Context
Find resources that will be used for the assignments.

# Task List
- [x] Image (Lorem Picsum)
- [x] Display font (Google fonts)
- [x] Body font (Google fonts)

# Definition of done
When they all go well together to my idea in mind.
