### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by myka-p** [myka-p/cpnt260-a2#5]
# Context
check this lists before submitting the assignment

# Task List
- [x] short heading and paragraph
- [x] Image (Lorem Picsum)
- [x] use valid `HTML` and `CSS` (desktop and mobile compatible)
- [x] place card in index.html (CSS can be appended in the head)

# Definition of done
If everything has been done and ready for submission.
