### ISSUE TITLE
Card content

### ISSUE THREAD

**Issue by myka-p** [myka-p/cpnt260-a2#6]
# Context
check this list before submitting the assignment

# Task List
- [x] one `<h3>` for card title in **Display font**
- [x] place holder HTML image **-alt, width, & height attributes**
- [ ] short `<p>` and `<body>` - has bold and/or italic **in Body text font**
- [x] card content should be wrapped in an `<article>` element

# Definition of done
If everything has been done and ready for submission.
