### ISSUE TITLE
Responsiveness & Accessibility

### ISSUE THREAD

**Issue by myka-p** [myka-p/cpnt260-a2#7]
# Context
check this list before submitting the assignment

# Task List
- [x] line length should not exceed `40ch` on wide screens
- [x] image not distorted and scale to fit the card
- [ ] no horizontal scroll
- [ ] `0.5rem` away from edge on mobile
- [x] ar least AA contrast ratio

# Definition of done
If everything has been done and ready for submission.
