### ISSUE TITLE
Clickable card

### ISSUE THREAD

**Issue by myka-p** [myka-p/cpnt260-a2#8]
# Context
check this list before submitting the assignment

# Task List
- [x] entire card should be clickable, no gaps (can link to any external link)
- [x] should have a visible boundary
- [x] clickable are should not exceed card boundary
- [x] no links inside the card
- [x] hover effect on links

# Definition of done
If everything has been done and ready for submission.
